# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cardsmobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SDWebImage'
  # Pods for cardsmobile

  target 'cardsmobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cardsmobileUITests' do
    # Pods for testing
  end

end
